version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
  apt_packages:
    - mongodb
  jobs:
    pre_build:
      - echo "Starting mongodb"
      - sudo service mongodb start

python:
  install:
    - requirements: requirements-doc.txt

sphinx:
  configuration: docs/conf.py
