# automatically generated from https://codemeta.github.io/terms/
from rdflib.namespace import Namespace
from rdflib.term import URIRef


class _CODEMETA:
    Organization = URIRef("https://schema.org/Organization")
    Person = URIRef("https://schema.org/Person")
    SoftwareSourceCode = URIRef("https://schema.org/SoftwareSourceCode")
    SoftwareApplication = URIRef("https://schema.org/SoftwareApplication")
    Text = URIRef("https://schema.org/Text")
    URL = URIRef("https://schema.org/URL")
    address = URIRef("https://schema.org/address")
    affiliation = URIRef("https://schema.org/affiliation")
    applicationCategory = URIRef("https://schema.org/applicationCategory")
    applicationSubCategory = URIRef("https://schema.org/applicationSubCategory")
    citation = URIRef("https://schema.org/citation")
    codeRepository = URIRef("https://schema.org/codeRepository")
    contributor = URIRef("https://schema.org/contributor")
    copyrightHolder = URIRef("https://schema.org/copyrightHolder")
    copyrightYear = URIRef("https://schema.org/copyrightYear")
    creator = URIRef("https://schema.org/creator")
    dateCreated = URIRef("https://schema.org/dateCreated")
    dateModified = URIRef("https://schema.org/dateModified")
    datePublished = URIRef("https://schema.org/datePublished")
    description = URIRef("https://schema.org/description")
    downloadUrl = URIRef("https://schema.org/downloadUrl")
    email = URIRef("https://schema.org/email")
    editor = URIRef("https://schema.org/editor")
    encoding = URIRef("https://schema.org/encoding")
    familyName = URIRef("https://schema.org/familyName")
    fileFormat = URIRef("https://schema.org/fileFormat")
    fileSize = URIRef("https://schema.org/fileSize")
    funder = URIRef("https://schema.org/funder")
    givenName = URIRef("https://schema.org/givenName")
    hasPart = URIRef("https://schema.org/hasPart")
    identifier = URIRef("https://schema.org/identifier")
    installUrl = URIRef("https://schema.org/installUrl")
    isAccessibleForFree = URIRef("https://schema.org/isAccessibleForFree")
    isPartOf = URIRef("https://schema.org/isPartOf")
    keywords = URIRef("https://schema.org/keywords")
    license = URIRef("https://schema.org/license")
    memoryRequirements = URIRef("https://schema.org/memoryRequirements")
    name = URIRef("https://schema.org/name")
    operatingSystem = URIRef("https://schema.org/operatingSystem")
    permissions = URIRef("https://schema.org/permissions")
    position = URIRef("https://schema.org/position")
    processorRequirements = URIRef("https://schema.org/processorRequirements")
    producer = URIRef("https://schema.org/producer")
    programmingLanguage = URIRef("https://schema.org/programmingLanguage")
    provider = URIRef("https://schema.org/provider")
    publisher = URIRef("https://schema.org/publisher")
    relatedLink = URIRef("https://schema.org/relatedLink")
    releaseNotes = URIRef("https://schema.org/releaseNotes")
    runtimePlatform = URIRef("https://schema.org/runtimePlatform")
    sameAs = URIRef("https://schema.org/sameAs")
    softwareHelp = URIRef("https://schema.org/softwareHelp")
    softwareRequirements = URIRef("https://schema.org/softwareRequirements")
    softwareVersion = URIRef("https://schema.org/softwareVersion")
    sponsor = URIRef("https://schema.org/sponsor")
    storageRequirements = URIRef("https://schema.org/storageRequirements")
    supportingData = URIRef("https://schema.org/supportingData")
    targetProduct = URIRef("https://schema.org/targetProduct")
    url = URIRef("https://schema.org/url")
    version = URIRef("https://schema.org/version")
    author = URIRef("https://schema.org/author")
    softwareSuggestions = URIRef("https://codemeta.github.io/terms/softwareSuggestions")
    contIntegration = URIRef("https://codemeta.github.io/terms/contIntegration")
    buildInstructions = URIRef("https://codemeta.github.io/terms/buildInstructions")
    developmentStatus = URIRef("https://codemeta.github.io/terms/developmentStatus")
    embargoDate = URIRef("https://codemeta.github.io/terms/embargoDate")
    funding = URIRef("https://codemeta.github.io/terms/funding")
    readme = URIRef("https://codemeta.github.io/terms/readme")
    issueTracker = URIRef("https://codemeta.github.io/terms/issueTracker")
    referencePublication = URIRef("https://codemeta.github.io/terms/referencePublication")
    maintainer = URIRef("https://codemeta.github.io/terms/maintainer")

    _NS = Namespace("https://codemeta.github.io/terms/")



CODEMETA = _CODEMETA()