"""constants used by the h5rdmtoolbox package"""

ANCILLARY_DATASET = 'ANCILLARY_DATASETS'
IRI_OBJECT_ATTR_NAME = 'IRI_OBJECT'
IRI_PREDICATE_ATTR_NAME = 'IRI_PREDICATE'
IRI_SUBJECT_ATTR_NAME = 'IRI_SUBJECT'
