"""constants used by the h5rdmtoolbox package"""

ANCILLARY_DATASET = 'ANCILLARY_DATASETS'
RDF_OBJECT_ATTR_NAME = 'RDF_OBJECT'
RDF_PREDICATE_ATTR_NAME = 'RDF_PREDICATE'
# RDF_SUBJECT_ATTR_NAME = 'IRI_SUBJECT'  # '@type'
RDF_SUBJECT_ATTR_NAME = '@type'
# IRI_TYPE_ATTR_NAME = '@type'
