# https://github.com/py-cov-action/python-coverage-comment-action-example/blob/master/.github/workflows/coverage.yml

name: Post coverage comment

on:
  workflow_run:
    workflows: ["tests"]
    types:
      - completed

jobs:
  test:
    name: Run tests & display coverage
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'push' && github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Post comment
        uses: py-cov-action/python-coverage-comment-action@v2
        with:
          VERBOSE: true