# github action including pymongo see https://github.com/marketplace/actions/mongodb-in-github-actions

name: Tests

on:
  push:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        python-version: [ '3.8', '3.9' , '3.10']

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions

      - name: Run pytest with tox
        run: |
          tox
