name: Tests

on:
  push:
#    branches:
#      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, ]
        python-version: ['3.8', ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Test with tox
      run: tox

    # from https://github.com/py-cov-action/python-coverage-comment-action-example/blob/master/.github/workflows/ci.yml
    - name: Coverage comment
      if: matrix.os == 'ubuntu-latest'
      id: coverage_comment
      uses: py-cov-action/python-coverage-comment-action@v2
      with:
        GITHUB_TOKEN: ${{ github.token }}
        VERBOSE: true

    # from https://github.com/py-cov-action/python-coverage-comment-action-example/blob/master/.github/workflows/ci.yml
    - name: Store Push Request comment to be posted
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v2
      if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
      with:
        # If you use a different name, update COMMENT_ARTIFACT_NAME accordingly
        name: python-coverage-comment-action
        # If you use a different name, update COMMENT_FILENAME accordingly
        path: python-coverage-comment-action.txt